---
- name: Create Azure CentOS VM
  hosts: localhost
  vars:
    resource_group: "{{ resource_group_name }}"
    vm_name: "{{ vmname }}"
  tasks:

    - name: Create CentOS VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: Standard_DS1_v2
        admin_username: gbmadmin
        admin_password: YourStrongPassword123!
       # network_interface_names: myNIC{{ vm_name }}
        image:
          offer: centos
          publisher: openlogic
          sku: '8_2-ARM'
          version: latest
      #  data_disks:
      #    disk_size_gb: 35
      #    lun: 01
          
       # ssh_public_keys:
       #   - path: /home/azureuser/.ssh/authorized_keys
       #     key_data: "{{ lookup('file', '/path/to/your/public/key.pub') }}"
        tags:
          Created_by: Radhika

