# Description
# ===========
# This playbook create a MySQL server and an instance of MySQL Database,

---
- name: Play to create DB server
  hosts: localhost
  vars:
    resource_group: "{{ resource_group_name }}"
    mysqlserver_name: "{{ server_name }}"
    mysqldb_name: "{{ db_name }}"
    admin_username: gbmadmin
    admin_password: Abcpasswordxyz12!
  tasks:
    - name: Create MySQL Server
      azure_rm_mysqlserver:
        resource_group: "{{ resource_group }}"
        name: "{{ mysqlserver_name }}"
        sku:
          #name: GP_Gen4_2
          #name: B_Gen5_1
          name: Standard_D2s_v3
          #tier: Basic
          tier: GeneralPurpose
          capacity: 2
          #family: Gen5
        #location: "{{ location }}"
        version: '8.0'
        enforce_ssl: True
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        storage_profile:
          storage_mb: 51200
        tags:
          Created_by: Radhika

    - name: Create instance of MySQL Database
      azure_rm_mysqldatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ mysqlserver_name }}"
        name: "{{ mysqldb_name }}"
