# Description
# ===========
# This playbook create a PostgreSQL server and an instance of PostgreSQL Database

---
- name: Play1 to create random postfix number
  hosts: localhost
  tasks:
#    - name: Prepare random postfix
 #     set_fact:
  #      rpfx: "{{ 1000 | random }}"
   #   run_once: yes

- name: Play2 to create DB server and instance
  hosts: localhost
  #roles:
  #  - azure.azure_preview_modules
  vars:
    resource_group: "{{ resource_group_name }}"
   # location: westeurope
   # postgresqlserver_name: postgresql{{ rpfx }}
    postgresqlserver_name: "{{ pgserver_name }}"
   # postgresqldb_name: sqldbtest
    postgresqldb_name: "{{ pgdb_name }}"
    admin_username: gbmadmin
    admin_password: Abcpasswordxyz12!
  tasks:
    - name: Create PostgreSQL Server
      azure_rm_postgresqlserver:
        resource_group: "{{ resource_group }}"
        name: "{{ postgresqlserver_name }}"
        sku:
          name: B_Gen5_1
          tier: Basic
          capacity: 1
        #location: "{{ location }}"
        enforce_ssl: True
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        storage_mb: 51200
        tags: 
          Created_by: Radhika

    - name: Create instance of PostgreSQL Database
      azure_rm_postgresqldatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ postgresqlserver_name }}"
        name: "{{ postgresqldb_name }}"
      
