---
- name: Create Azure VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VM with defaults
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        admin_username: "mctsuser"
        admin_password: "Mcts@1234"
        vm_size: Standard_B1s
        image:
          offer: 0001-com-ubuntu-server-jammy
          publisher: Canonical
          sku: 22_04-lts
          version: latest
        state: present
