---
- name: Create Azure VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VM with defaults
      azure_rm_virtualmachine:
        resource_group: CloudX_test
        name: im-testvm
        admin_username: "mctsuser"
        image:
          offer: 0001-com-ubuntu-server-jammy
          publisher: Canonical
          sku: 22_04-lts
          version: latest
        state: present
