---
- name: Create Azure Windows VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VM with defaults
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        admin_username: "mctsadmin"
        admin_password: "Mcts@1234"
        vm_size: Standard_B1s
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2016-Datacenter
          version: latest
        state: present
        tags: 
          Created_by: Radhika
