- name: Get python, ansible versions
  hosts: localhost
  tasks:
    - name: Get python version
      command:
        cmd: ["ansible --version", "python --version", "echo $ANSIBLE_PYTHON_INTERPRETER"]
