- name: Get python, ansible versions
  hosts: localhost
  tasks:
    - name: Get python version
      command: "{{ item }}"
      with_items:
        - "ansible --version"
        - "python --version"
        - "echo $ANSIBLE_PYTHON_INTERPRETER"
