- name: Get python, ansible versions
  hosts: localhost
  tasks:
    - name: Get python version
      command: "{{ item }}"
      with_items:
        - "ansible --version"
        - "python3 --version"
      register: output

    - name: Print output
      debug:
        var: output
