---
- name: HMC create and activate logical partition
  hosts: localhost
  #vars:
#      curr_hmc_auth:
 #         username: hscroot
  #        password: abc123
  collections:
    - ibm.power_hmc

  tasks:
      - name: Installing zhmcclient python library using Ansible pip module
        pip:
          name: zhmcclient
          
      - name: Create logical partition with mem, shared proc, storage, network config and npiv
        ibm.power_hmc.powervm_lpar_instance:
        #    hmc_auth: "{{ curr_hmc_auth }}"
           # system_name: zepp31fp
            vm_name: rj-partition1
            proc: 2
            proc_unit: 2
            mem: 2048
            os_type: aix
            max_virtual_slots: 50
            state: present
        register: testout

      - name: Stdout the created logical partition
        ansible.builtin.debug:
            msg: '{{ testout }}'

      - name: Activate logical partition with default profile and keylock config
        ibm.power_hmc.powervm_lpar_instance:
        #    hmc_host: '{{ inventory_hostname }}'
        #    hmc_auth: "{{ curr_hmc_auth }}"
        #    system_name: zepp31fp
            vm_name: rj-partition1
            keylock: normal
            action: poweron
