---
- name: Get engine versions
  hosts: localhost
  tasks:
    - name: Get default engine version for DB parameter group family postgres16
      amazon.aws.rds_engine_versions_info:
        engine: "{{ engine }}"
        region: us-east-1


