
---
- name: Get AWS VPC and subnet info
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-east-1"
  tasks:
    - name: Get VPC details
      ec2_vpc_net_info:
        region: "us-east-1"
      register: result

    - name: Print VPC details
      debug:
        var: result

    - name: Get Subnet details
      ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ result.vpcs[0].vpc_id }}"
      register: subnet

    - name: Print subnet details
      debug:
        msg: "{{ subnet.subnets[0].subnet_id }}"
