---
- name: create-rds-intance
  hosts: localhost
  gather_facts : false

  tasks:
    - name: provision oracle rds intance
      amazon.aws.rds_instance:      
        db_instance_identifier: "{{ db_identifier }}"
        db_name: "{{ db_name }}"
        state: present
        engine: postgres
        #engine_version: 14.11
        engine_version: 14.15
        username: "root"
        password: "Password123"
        db_instance_class: "{{ db_size_class }}"
        allocated_storage: "100"
        region: "us-east-1"
        tags:
          Created_by: Radhika
