---      
- name: Create a VMware VM from CentOS template
  hosts: localhost
  gather_facts: no
  vars:
    vmname: "{{ name }}"
  tasks:
  - name: Clone the template
    vmware_guest:
      validate_certs: False
      name: "{{ vmname }}"
      template: "RHEL8-tmp"
      datacenter: CloudX
      folder: "VMs"
      state: poweredon
   #   networks:
   #     - name: "Internal Network"
   #      type: dhcp
    register: vm


- name: Print
  hosts: localhost
  tasks:
    - debug:
        var: hostvars.localhost.vm
    
