---      
- name: Create a VMware VM from RHEL template
  hosts: localhost
  gather_facts: no
  vars:
    vmname: "{{ name }}"
    pkg: "{{ package }}"
  tasks:
  - name: Clone the template
    vmware_guest:
      validate_certs: False
      name: "{{ vmname }}"
      template: "centos-test"
      datacenter: CloudX
      folder: "VMs"
      state: poweredon
      networks:
        - name: "Internal Network"
          type: dhcp
          connected: true
      wait_for_ip_address: true
    register: vm

  - name: Wait for SSH
    wait_for:
      port: 22
      host: "{{ vm.instance.ip }}"
      delay: 10
      timeout: 300

  - name: Install package
    ansible.builtin.yum:
      name: "{{ pkg }}"
      state: present
    delegate_to: "{{ vm.instance.ip }}"
    become: yes
    
