---
- name: Create Oracle Cloud VM Instance
  hosts: localhost
  tasks:
    - name: Launch a new VM instance
      oracle.oci.oci_instance:
        compartment_id: "ocid1.tenancy.oc1..aaaaaaaaa7r6ogjtqlv53fkqqtqvnkxdxqq4fzmhs2zeoixqvy3yby4ayz4a"
        availability_domain: "AD-1"
        display_name: "my-vm-instance"
        shape: "VM.Standard.E5.Flex"  # Change as needed
        image: "ocid1.image.oc1.me-dubai-1.aaaaaaaartavz27mnra44bihak3wqwt3xjtl6rjp75mvhqm7fde5u45w5ssa"  # Replace with your image OCID
        subnet_id: "ocid1.subnet.oc1.me-dubai-1.aaaaaaaazyg4s46gwhrwbp227nmjvwpektrtztlpqoecoad27o432326v6xq"
        assign_public_ip: false
        metadata: null
        state: present
      register: instance

    - name: Output instance details
      debug:
        var: instance
