---
- name: Get instance details
  hosts: localhost
  tasks:
    - name: Installing oci python library using Ansible pip module
      pip:
        name: oci

    - name: Get a specific instance
      oracle.oci.oci_compute_instance_facts:
       # required
        instance_id: "ocid1.instance.oc1.me-dubai-1.anshqljr3facxyycjxhhlj2gzqdlnq4uon6ip7udnc2sra4rryyy6putdbya"
